name: Environment Status

on:
  workflow_dispatch: {}

jobs:
  qa:
    permissions:
      deployments: write
    uses: Solierrr/.github/.github/workflows/environment-status.yml@main
    with:
      environment: QA
      check: http
      url: https://web-app-ldi0.onrender.com

  production:
    permissions:
      deployments: write
    uses: Solierrr/.github/.github/workflows/environment-status.yml@main
    with:
      environment: PROD
      check: gcloud-cluster
      gcp_project_id: solaria-authenticator
      gcp_cluster_name: solaria-gke
      gcp_zone: us-central1-a
    secrets:
      GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
